name: Trigger Stats Obtaination

on:
  schedule:
    - cron: "42 * * * *"

env:
  KEY: ${{secrets.SITE_API_KEY}}

jobs:
  build:
    name: Trigger Stats Obtaination
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X GET https://bedstats-site.vercel.app/api/users/recordstats?key=$KEY
